version: '3.8'

services:
  db:
    image: postgres:15.0-alpine
    container_name: "db"
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=collection
    ports:
      - "5432:5432"